version: '3'

services:
  # Flask API Service
  web:
    image: python:3.10
    command: bash -c "pip install -r /app/requirements.txt && python /app/app.py"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
          - .env

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:apache
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html/

volumes:
  pg_data:
